-- DOWN: reverte migration 002 (RLS policies + helpers)

-- Helpers
DROP FUNCTION IF EXISTS current_user_role() CASCADE;
DROP FUNCTION IF EXISTS user_turma_ids()   CASCADE;
DROP FUNCTION IF EXISTS user_unidade_ids() CASCADE;
DROP FUNCTION IF EXISTS user_marca_ids()   CASCADE;

-- Desabilitar RLS em todas as tabelas
ALTER TABLE audit_log       DISABLE ROW LEVEL SECURITY;
ALTER TABLE resultado        DISABLE ROW LEVEL SECURITY;
ALTER TABLE inscricao        DISABLE ROW LEVEL SECURITY;
ALTER TABLE olimpiada_fase   DISABLE ROW LEVEL SECURITY;
ALTER TABLE olimpiada_marca  DISABLE ROW LEVEL SECURITY;
ALTER TABLE olimpiada        DISABLE ROW LEVEL SECURITY;
ALTER TABLE convite          DISABLE ROW LEVEL SECURITY;
ALTER TABLE usuario_turma    DISABLE ROW LEVEL SECURITY;
ALTER TABLE usuario_unidade  DISABLE ROW LEVEL SECURITY;
ALTER TABLE usuario_marca    DISABLE ROW LEVEL SECURITY;
ALTER TABLE usuario          DISABLE ROW LEVEL SECURITY;
ALTER TABLE aluno            DISABLE ROW LEVEL SECURITY;
ALTER TABLE turma            DISABLE ROW LEVEL SECURITY;
ALTER TABLE unidade          DISABLE ROW LEVEL SECURITY;
ALTER TABLE marca            DISABLE ROW LEVEL SECURITY;
